# -*- coding: utf-8 -*-
"""example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RM83lHspBVT9EAhz-ozjlsHL1DqbjPfW
"""

class Bank:
    def __init__(self, name, count, amount, rate):
        self.bank_name = name
        self.deposit_count = count
        self.deposit_amount = amount
        self.interest_rate = rate

    def calculate_total_interest(self):
        total_deposits = self.deposit_count * self.deposit_amount
        return total_deposits * (self.interest_rate / 100.0)

    def display_info(self):
        print(f"Наименование банка: {self.bank_name}")
        print(f"Число вкладов: {self.deposit_count}")
        print(f"Размер одного вклада: {self.deposit_amount}")
        print(f"Процентная ставка: {self.interest_rate}%")
        print(f"Общая выплата по процентам: {self.calculate_total_interest()}")


def input_with_validation(prompt, validation_fn, error_msg):
    while True:
        try:
            value = validation_fn(input(prompt))
            return value
        except ValueError:
            print(error_msg)


if __name__ == "__main__":
    name = input("Введите наименование банка: ")

    count = input_with_validation(
        "Введите число вкладов (от 0 до 100): ",
        lambda x: int(x) if 0 <= int(x) <= 100 else ValueError,
        "Ошибка: количество вкладов должно быть целым числом от 0 до 100."
    )

    amount = input_with_validation(
        "Введите размер одного вклада (от 10 до 10000): ",
        lambda x: float(x) if 10 <= float(x) <= 10000 else ValueError,
        "Ошибка: размер вклада должен быть числом от 10 до 10000."
    )

    rate = input_with_validation(
        "Введите процентную ставку (от 0 до 100): ",
        lambda x: float(x) if 0 <= float(x) <= 100 else ValueError,
        "Ошибка: процентная ставка должна быть числом от 0 до 100."
    )

    # Создание объекта класса Bank с введенными значениями
    bank = Bank(name, count, amount, rate)

    # Вывод информации и расчет общей выплаты по процентам
    bank.display_info()print("Hello, world!")